// <auto-generated />
using MasterDetail.Web.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MasterDetail.Web.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class BloggingDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MasterDetail.Web.Model.Person", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Family");

                    b.Property<string>("Name");

                    b.Property<string>("NationalCode");

                    b.Property<bool>("Subscribed");

                    b.HasKey("Id");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("MasterDetail.Web.Model.PersonPost", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("PersonId");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonPost");
                });

            modelBuilder.Entity("MasterDetail.Web.Model.PersonPostDetail", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FromDate");

                    b.Property<string>("PersonPostId");

                    b.Property<string>("ToDate");

                    b.HasKey("Id");

                    b.HasIndex("PersonPostId");

                    b.ToTable("PersonPostDetail");
                });

            modelBuilder.Entity("MasterDetail.Web.Model.PersonPost", b =>
                {
                    b.HasOne("MasterDetail.Web.Model.Person")
                        .WithMany("ThePersonPostList")
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("MasterDetail.Web.Model.PersonPostDetail", b =>
                {
                    b.HasOne("MasterDetail.Web.Model.PersonPost")
                        .WithMany("ThePersonPostDetailList")
                        .HasForeignKey("PersonPostId");
                });
#pragma warning restore 612, 618
        }
    }
}
